# Generated by Django 4.0.1 on 2022-02-03 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affairs', '0002_intake'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='email',
        ),
    ]
